pool:
  name: default
stages:

- stage: DEV
  lockBehavior: sequential
  jobs:
  - deployment: 'DeployToQA'
    environment: 'fares'
    strategy:
        runOnce:
          deploy:
            steps:
              - task: AzureWebApp@1
                inputs:
                  azureSubscription: 'Valorem(04c7f982-87f9-4fa5-8da8-7a1f76e7b15d)'
                  appType: 'webApp'
                  appName: 'migration-web-app'
                  package: '$(System.DefaultWorkingDirectory)/*.zip'
                  deploymentMethod: 'auto'

- stage: DB
  jobs:
  - job: Deploy
    steps:
    - task: SqlAzureDacpacDeployment@1
      inputs:
        azureSubscription: 'Valorem(04c7f982-87f9-4fa5-8da8-7a1f76e7b15d)'
        AuthenticationType: 'connectionString'
        ConnectionString: 'Server=tcp:migration-sql-db.database.windows.net,1433;Initial Catalog=tourdb;Persist Security Info=False;User ID=Dalyne1999;Password=Backtrack5r3;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
        deployType: 'DacpacTask'
        DeploymentAction: 'Import'
        BacpacFile: 'tourdb-2023-5-19-13-38.dacpac'
        IpDetectionMethod: 'AutoDetect'



