variables:
  isMain: fares
pool:
  name: default
stages:

- stage: DEV
  lockBehavior: sequential
  jobs:
  - deployment: 'DeployToQA'
    environment: 'fares'
    strategy:
        runOnce:
          deploy:
            steps:
              - task: DotNetCoreCLI@2
                inputs:
                  command: 'build'
                  projects: '$(System.DefaultWorkingDirectory)/DotNetFrameworkProject_CE040_CE087/Tour_Management.sln'
              - task: CmdLine@2
                inputs:
                  script: |
                    echo Write your commands here
                    cd DotNetFrameworkProject_CE040_CE087
                    cd Tour_Management
                    ls -a
                    pwd
                    echo Hello world/
              - task: AzureWebApp@1
                inputs:
                  azureSubscription: 'Valorem(04c7f982-87f9-4fa5-8da8-7a1f76e7b15d)'
                  appType: 'webApp'
                  appName: 'pipeline-test-webapp'
                  package: '$(System.DefaultWorkingDirectory)/*.zip'
                  deploymentMethod: 'auto'

- stage: DB
  jobs:
  - job: Deploy
    steps:
    - task: SqlAzureDacpacDeployment@1
      inputs:
        azureSubscription: 'Valorem(04c7f982-87f9-4fa5-8da8-7a1f76e7b15d)'
        AuthenticationType: 'connectionString'
        ConnectionString: 'Server=tcp:migration-sql-db.database.windows.net,1433;Initial Catalog=tourdb;Persist Security Info=False;User ID=Dalyne1999;Password=Backtrack5r3;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;'
        deployType: 'DacpacTask'
        DeploymentAction: 'Import'
        BacpacFile: 'tourdb-2023-5-19-13-38.dacpac'
        IpDetectionMethod: 'AutoDetect'



