variables:
  isMain: fares
pool:
  name: default
stages:
- stage: DEV
  jobs:
  - job: Deploy
    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            # Write your PowerShell commands here.
            dotnet publish
            $compress = @{
              Path = "$(System.DefaultWorkingDirectory)/bin/Debug/net7.0/publish/*"
              CompressionLevel = "Fastest"
              DestinationPath = "$(System.DefaultWorkingDirectory)/$(deployzip).zip"
            }
            Compress-Archive @compress
      - task: AzureWebApp@1
        inputs:
          azureSubscription: 'Valorem(04c7f982-87f9-4fa5-8da8-7a1f76e7b15d)'
          appType: 'webApp'
          appName: 'api-finance-project'
          package: '$(System.DefaultWorkingDirectory)/$(deployzip).zip'
          deploymentMethod: 'auto'
- stage: QA
  lockBehavior: sequential
  jobs:
  - deployment: 'DeployToQA'
    environment: 'fares'
    strategy:
        runOnce:
          deploy:
            steps:
              - task: PowerShell@2
                inputs:
                  targetType: 'inline'
                  script: |
                    # Write your PowerShell commands here.
                    dotnet publish
                    $compress = @{
                    Path = "$(System.DefaultWorkingDirectory)/bin/Debug/net7.0/publish/*"
                    CompressionLevel = "Fastest"
                    DestinationPath = "$(System.DefaultWorkingDirectory)/$(deployzip).zip"
                    }
                    Compress-Archive -Force @compress
              - task: AzureWebApp@1
                inputs:
                  azureSubscription: 'Valorem(04c7f982-87f9-4fa5-8da8-7a1f76e7b15d)'
                  appType: 'webApp'
                  appName: 'pipeline-test-webapp'
                  package: '$(System.DefaultWorkingDirectory)/*.zip'
                  deploymentMethod: 'auto'


